use anyhow::Result;
use clap::Parser;
use futures::{future, prelude::*};
use std::net::{IpAddr, Ipv6Addr};
use std::path::PathBuf;
use tarpc::{
  server::{self, Channel},
  tokio_serde::formats::Json,
};
use yosys_service::Synthesis;
use yosys_service::server::SynthesisServer;

async fn spawn(fut: impl Future<Output = ()> + Send + 'static) {
  tokio::spawn(fut);
}

#[derive(Parser, Debug)]
struct Args {
  #[arg(long, default_value_t = 8080)]
  port: u16,
  #[arg(long, default_value = "yosys")]
  yosys_path: PathBuf,
}

#[tokio::main]
async fn main() -> Result<()> {
  let flags = Args::parse();
  let server_addr = (IpAddr::V6(Ipv6Addr::LOCALHOST), flags.port);

  let mut listener = tarpc::serde_transport::tcp::listen(server_addr, Json::default).await?;
  listener.config_mut().max_frame_length(usize::MAX);

  println!("yosys_server");
  println!("\tListening on port: {}", flags.port);
  println!("\tUsing Yosys path:  {}", flags.yosys_path.display());

  listener
    // Ignore accept errors.
    .filter_map(|r| future::ready(r.ok()))
    .map(server::BaseChannel::with_defaults)
    // serve is generated by the service attribute. It takes as input any type implementing
    // the generated World trait.
    .map(|channel| {
      let server = SynthesisServer {
        yosys_path: flags.yosys_path.clone(),
      };
      channel.execute(server.serve()).for_each(spawn)
    })
    // Max 10 channels.
    .buffer_unordered(10)
    .for_each(|_| async {})
    .await;
  Ok(())
}
